k<CONNECT>
CONN / AS SYSDBA

-- <CREATE NEW USER SMS>
CREATE USER SMS IDENTIFIED BY SMSSYSTEM QUOTA UNLIMITED ON USERS;
CREATE USER SMS IDENTIFIED BY SMSSYSTEM  QUOTA UNLIMITED ON mytablespace;

-- <GRANT ACCESS>
GRANT CREATE SESSION TO SMS;  --revoke;
GRANT RESOURCE TO SMS;

-- <CONNECT WITH USER>
CONN SMS/SMSSYSTEM;

-- <CREATE TABLE STUDENT WITH ID>
CREATE TABLE STUDENT(ID NUMBER(10));

-- <SELECT DATA FROM USER TABLE>
SELECT *FROM STUDENT;
SELECT *FROM SMS.STUDENT;

-- <VIEW TABLE IN CURRENT USER DIR>
SELECT * FROM TAB;

-- <GRANT ANOTHER TO ACCESS THAT TABLE>
GRANT SELECT ON STUDENT TO REPORTER;

<show current user>
show user

<CREATE TABLE SPACE>
CREATE TABLESPACE employtablespace 
DATAFILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\employtablespace_01.DBF'
SIZE 100M AUTOEXTEND ON;


<DESCRIVE DATAFILE>
DESC V$DATAFILE; --data dictionary;
select name from v$datafile;
SELECT NAME,TS# FROM V$DATAFILE; --SHOW WHERE ALL DATAFILE STORE;
SELECT NAME,TS# FROM V$TABLESPACE;
SELECT NAME,TS# FROM V$DATAFILE WHERE TS#='4';

ddl ->  create drop ALTER truncate;
dml ->  insert delete update;
tcl -> commit rollback;
TABLE,views,sequence,synonym,function,procedure;

CREATE SEQUENCE EMP_PC START WITH 1; --CYCLE THE VALUE;
Create sequence sequence_name
start with value
increment by value
minvalue value
maxvalue value;

SELECT EMP_PIC.NEXTVAL FROM DUAL;-- EMP_PIC.CURRVAL;

CREATE TABLE OFFICE(ID NUMBER(3) PRIMARY KEY ,OFFICE_NAME VARCHAR(50) , ADDRESS1 VARCHAR(100),
	ADDRESS2 VARCHAR(100),CITY VARCHAR(50),STATE VARCHAR(50),PINCODE NUMBER(6)
);

CREATE TABLE DEPARTMENT(ID NUMBER(3) PRIMARY KEY,NAME VARCHAR(50));

CREATE TABLE Employee(ID NUMBER(10) PRIMARY KEY ,PAN NUMBER(10) ,NAME VARCHAR(30),DOB DATE,OFFICE_ID
	NUMBER(5), FOREIGN KEY (OFFICE_ID) REFERENCES OFFICE(ID) ,DEPT_ID
	NUMBER(5),  FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID),
	CONTACT_NO NUMBER(11),EMAIL VARCHAR(50),
	GENDER CHAR(1),PHY_CHALLANGED CHAR(1)
);

posgress n  mysql;

-- INSERT INTO Employee values(
-- 	,'VISHNU MISHRA',TO_DATE('05-DEC-1993','DD-MON-YYYY'),
-- 	'H.NO-30 JEETRAM COLONY','BUDHPUR',	'DELHI','DELHI',
-- 	110036,	8459070976,'vishnu143mishra@gmail.com',
-- 	'M','N');



CREATE TABLE STUDENT(ID NUMBER(10) PRIMARY KEY ,
	NAME VARCHAR(30),	DOB DATE,ADDRESS1 VARCHAR(100 ),
	ADDRESS2 VARCHAR(100),CITY VARCHAR(50),STATE VARCHAR(50),
	PINCODE NUMBER(6),CONTACT_NO NUMBER(11),EMAIL VARCHAR(50),
	GENDER CHAR(1),PHY_CHALLANGED CHAR(1));

<ALTER>
alter table student
add constraint gender_ck CHECK(gender in ('M','F')) ;

alter table student
add MARK_3 NUMBER(3);

alter table student
add TOTAL NUMBER(3);


INSERT INTO STUDENT values(
	1011,'VISHNU MISHRA',TO_DATE('05-DEC-1993','DD-MON-YYYY'),
	'H.NO-30 JEETRAM COLONY','BUDHPUR',	'DELHI','DELHI',
	110036,	8459070976,'vishnu143mishra@gmail.com',
	'M','N');
INSERT INTO STUDENT values(
	1002,'ANKUR',TO_DATE('01-JAN-1993','DD-MON-YYYY'),
	'H.NO-1 PAN MOHALLA','BHALASWA','HARDOI','UTTAR PRADESH',
	410431,	987654321,'ANKUR@gmail.com',
	'M','N');

INSERT INTO STUDENT values(
	1003,'JP',TO_DATE('07-07-1992','DD-MM-YYYY'),
	'1/680 ','VIKAS NAGAR','LUCKNOW','UTTAR PRADESH',
	226022,	8553245896,'jplko.simt@gmail.com',
	'M','N');

INSERT INTO STUDENT values(
	1004,'MAHESH',TO_DATE('02-03-1992','DD-MM-YYYY'),
	'3/4','PLUTO','PLUTO','COSMOS',
	900009,	9999999999,'MAHESHASUR@gmail.com',
	'M','N');

INSERT INTO STUDENT values(
	1005,'PRASHANT',TO_DATE('01-08-1991','DD-MM-YYYY'),
	'CHOR MOHHALA','PANWALI GALI','LUCKNOW','UTTAR PRADESH',
	226022,9887766552,'PRASHANT@gmail.com',
	'M','N');

INSERT INTO STUDENT values(
	1006,'PERMATAMA',TO_DATE('30-03-1990','DD-MM-YYYY'),
	'786/4','BHOTOWALI GALI','HARRIYA','UTTAR PRADESH',
	226022,1023456789,'PERMATAMA@gmail.com',
	'M','N');

INSERT INTO STUDENT values(
	1007,'BHANGARU',TO_DATE('02-12-1989','DD-MM-YYYY'),
	'420/2','BHANGAR WALI','KABADA MARKET','GRBAGE NAGAR',
	231256,1023498563,'BHANGAR@gmail.com',
	'M','N');

INSERT INTO STUDENT values(
	1008,'SHARMILLA',TO_DATE('23-12-1986','DD-MM-YYYY'),
	'420/420','EMILIKA PADE','KHUFIYA NAGAR','PAREM GALI',
	420420,173454573,'SHARMILLA@gmail.com',
	'F','N');

INSERT INTO STUDENT values(
	1009,'CHAMELI BAI',TO_DATE('23-12-1994','DD-MM-YYYY'),
	'CHAMPA WALI GALI','PHUAL GAON','GULAB GANJ','UTTAR PRADESH',
	123123,1232343456,'CHAMELI_BAI@gmail.com',
	'F','N');

INSERT INTO STUDENT values(
	1010,'GHADHAPRASAD',TO_DATE('09-03-1985','DD-MM-YYYY'),
	'BANARGHATTA ZOO','BANARGHATTA','JANGALPUR','KARNATAKA',
	321234,9999999999,'GHADHAPRASAD@ZOO.com',
	'F','N');

SELECT TO_CHAR(SYSDATE,'DD-MON-YYYY HH:MM:SS') FROM DATE;
INSERT TO_DATE('09/02/2015 10:15:00','DD-MM-YYYY HH:MI:SS');

SELECT NAME,ID FROM STUDENT WHERE MARK_1 > 60;
SELECT ID,NAME FROM STUDENT WHERE MARK_1 < 60 OR MARK_2 <60 OR MARK_3 < 60
select * from student;

<update >
update STUDENT SET MARK_1 = 67 WHERE ID =1000;
update STUDENT SET MARK_1 = 71, MARK_2=34, MARK_3 = 65 WHERE ID =1002;

UPDATE STUDENT SET TOTAL = MARK_1+MARK_2+MARK_3;

SELECT SUM(S1) FROM STUDENT;

